name: lab3
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyterlab
    - torch
    - tqdm
    - pyyaml
    - statsmodels
    - xgboost
    - transformers
    - 

